# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
# Default build settings
[build]
  publish = "public"
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"


# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_THEME = "docsy"
  HUGO_ENV = "production"

# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  # make sure you add a comma after each entry in the exclude list except on the last one
  exclude =[
    './public/**/**'
  ]
  # append missing trailing slash to prettyURL
  trailingSlash = true
  changeFreq = "weekly"
  priority = 0.5


# headers  https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# https://cloud-armory.slack.com/archives/CH4RVCCTS/p1608572781420500
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Robots-Tag = "noindex, nofollow"
